#!/bin/sh

# Copyright © 2009 Jakub Wilk <jwilk@jwilk.net>

# Redistribution and use in source and compiled forms, with or without
# modification, are permitted under any circumstances. No warranty.

if [ $# -ne 1 ]
then
  printf -- '%s <corpus-base-name>\n' "$0" >&2
  exit 1
fi
bytes=`stat --printf %s "$1.poliqarp.corpus.image"`
nseg=$((bytes/12))
exec poliqarpc -L $nseg -m -c0 "$1" '[]' \
| sed -re 's/^""," *(.*)",""$/\1/' \
| sort | uniq -c \
| sort -rn
