#!/bin/sh
if [ $# -ne 1 ]
then
  printf -- '%s <corpus-base-name>\n' "$0" >&2
  exit 1
fi
bytes=`stat --printf %s "$1.poliqarp.corpus.image"`
nseg=$((bytes/12))
exec poliqarpc -L $nseg -m -c0 "$1" '[]' \
| sed -re 's/^""," *(.*)",""$/\1/' \
| sort | uniq -c \
| sort -rn
