#!/usr/bin/python

import os

import django.core.management

if __name__ == "__main__":
    if django.VERSION < (1, 4):
        import settings
        django.core.management.execute_manager(settings)
    else:
        # https://docs.djangoproject.com/en/1.4/releases/1.4/#updated-default-project-layout-and-manage-py
        os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')
        django.core.management.execute_from_command_line()

# vim:ts=4 sw=4 et
